/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include <MyCvModuleImplFactory.hpp>
#include "MyCvModuleImpl.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>
#include "MediaPipelineImpl.hpp"

#define GST_CAT_DEFAULT kurento_my_cv_module_impl
GST_DEBUG_CATEGORY_STATIC (GST_CAT_DEFAULT);
#define GST_DEFAULT_NAME "KurentoMyCvModuleImpl"

namespace kurento
{
namespace module
{
namespace mycvmodule
{

MyCvModuleImpl::MyCvModuleImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline) : OpenCVFilterImpl (config, std::dynamic_pointer_cast<MediaPipelineImpl> (mediaPipeline))

{
}

void MyCvModuleImpl::setFilterType (int filterType)
{
  MyCvModuleOpenCVImpl::setFilterType (filterType);
}

void MyCvModuleImpl::setEdgeThreshold (int edgeValue)
{
  MyCvModuleOpenCVImpl::setEdgeThreshold (edgeValue);
}

MediaObjectImpl *
MyCvModuleImplFactory::createObject (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline) const
{
  return new MyCvModuleImpl (config, mediaPipeline);
}

MyCvModuleImpl::StaticConstructor MyCvModuleImpl::staticConstructor;

MyCvModuleImpl::StaticConstructor::StaticConstructor()
{
  GST_DEBUG_CATEGORY_INIT (GST_CAT_DEFAULT, GST_DEFAULT_NAME, 0,
                           GST_DEFAULT_NAME);
}

} /* mycvmodule */
} /* module */
} /* kurento */
