/* Autogenerated with kurento-module-creator */

#ifndef __MY_CV_MODULE_OPENCV_IMPL_HPP__
#define __MY_CV_MODULE_OPENCV_IMPL_HPP__

#include <OpenCVProcess.hpp>
#include "MyCvModule.hpp"
#include <EventHandler.hpp>

namespace kurento
{
namespace module
{
namespace mycvmodule
{

class MyCvModuleOpenCVImpl : public virtual OpenCVProcess
{

public:

  MyCvModuleOpenCVImpl ();

  virtual ~MyCvModuleOpenCVImpl() = default;

  virtual void process (cv::Mat &mat);

  void setFilterType (int filterType);
  void setEdgeThreshold (int edgeValue);

};

} /* mycvmodule */
} /* module */
} /* kurento */

#endif /*  __MY_CV_MODULE_OPENCV_IMPL_HPP__ */
